version: 1
accounts:
- name: alice
  coins:
  - 200000000test
- name: bob  
  coins:
  - 100000000stake
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 100000test
validators:
- name: alice
  bonded: 100000000test   
  config:
      consensus:
        timeout_commit: "30s"
        timeout_propose: "30s"
genesis:
  app_state:
    staking:
      params:
        bond_denom: "test"
    gov:
      deposit_params:
        min_deposit:
          - amount: "10000000"
            denom: "test"
    crisis:
      constant_fee:
        denom: "test"
    mint:
      params:
        mint_denom: "test"
